# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\QT_project\Visual_terminal\find_color_block.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_find_color_block(object):
    def setupUi(self, find_color_block):
        find_color_block.setObjectName("find_color_block")
        find_color_block.resize(1301, 866)
        self.groupBox_2 = QtWidgets.QGroupBox(find_color_block)
        self.groupBox_2.setGeometry(QtCore.QRect(650, 490, 161, 121))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(12)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.groupBox_2)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(10, 22, 141, 91))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.checkBox_Red = QtWidgets.QCheckBox(self.verticalLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(12)
        self.checkBox_Red.setFont(font)
        self.checkBox_Red.setObjectName("checkBox_Red")
        self.verticalLayout_6.addWidget(self.checkBox_Red)
        self.checkBox_Blue = QtWidgets.QCheckBox(self.verticalLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(12)
        self.checkBox_Blue.setFont(font)
        self.checkBox_Blue.setObjectName("checkBox_Blue")
        self.verticalLayout_6.addWidget(self.checkBox_Blue)
        self.checkBox_Yellow = QtWidgets.QCheckBox(self.verticalLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(12)
        self.checkBox_Yellow.setFont(font)
        self.checkBox_Yellow.setObjectName("checkBox_Yellow")
        self.verticalLayout_6.addWidget(self.checkBox_Yellow)
        self.groupBox = QtWidgets.QGroupBox(find_color_block)
        self.groupBox.setGeometry(QtCore.QRect(650, 610, 621, 241))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.frame = QtWidgets.QFrame(self.groupBox)
        self.frame.setGeometry(QtCore.QRect(0, 10, 631, 261))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 70, 601, 31))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.S_Slider_max = QtWidgets.QSlider(self.horizontalLayoutWidget_3)
        self.S_Slider_max.setOrientation(QtCore.Qt.Horizontal)
        self.S_Slider_max.setObjectName("S_Slider_max")
        self.horizontalLayout_3.addWidget(self.S_Slider_max)
        self.horizontalLayoutWidget_7 = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget_7.setGeometry(QtCore.QRect(10, 190, 601, 31))
        self.horizontalLayoutWidget_7.setObjectName("horizontalLayoutWidget_7")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_7)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_7 = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        self.TextEdit_hsv = QtWidgets.QPlainTextEdit(self.horizontalLayoutWidget_7)
        self.TextEdit_hsv.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(12)
        self.TextEdit_hsv.setFont(font)
        self.TextEdit_hsv.setPlainText("")
        self.TextEdit_hsv.setObjectName("TextEdit_hsv")
        self.horizontalLayout_7.addWidget(self.TextEdit_hsv)
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(10, 130, 601, 31))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.V_Slider_max = QtWidgets.QSlider(self.horizontalLayoutWidget_5)
        self.V_Slider_max.setOrientation(QtCore.Qt.Horizontal)
        self.V_Slider_max.setObjectName("V_Slider_max")
        self.horizontalLayout_5.addWidget(self.V_Slider_max)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(10, 100, 601, 31))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.S_Slider_min = QtWidgets.QSlider(self.horizontalLayoutWidget_4)
        self.S_Slider_min.setOrientation(QtCore.Qt.Horizontal)
        self.S_Slider_min.setObjectName("S_Slider_min")
        self.horizontalLayout_4.addWidget(self.S_Slider_min)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 40, 601, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.H_Slider_min = QtWidgets.QSlider(self.horizontalLayoutWidget_2)
        self.H_Slider_min.setOrientation(QtCore.Qt.Horizontal)
        self.H_Slider_min.setObjectName("H_Slider_min")
        self.horizontalLayout_2.addWidget(self.H_Slider_min)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 601, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.H_Slider_max = QtWidgets.QSlider(self.horizontalLayoutWidget)
        self.H_Slider_max.setOrientation(QtCore.Qt.Horizontal)
        self.H_Slider_max.setObjectName("H_Slider_max")
        self.horizontalLayout.addWidget(self.H_Slider_max)
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(10, 160, 601, 31))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.V_Slider_min = QtWidgets.QSlider(self.horizontalLayoutWidget_6)
        self.V_Slider_min.setOrientation(QtCore.Qt.Horizontal)
        self.V_Slider_min.setObjectName("V_Slider_min")
        self.horizontalLayout_6.addWidget(self.V_Slider_min)
        self.label_img = QtWidgets.QLabel(find_color_block)
        self.label_img.setGeometry(QtCore.QRect(0, 0, 640, 480))
        self.label_img.setText("")
        self.label_img.setObjectName("label_img")
        self.label_img_gray = QtWidgets.QLabel(find_color_block)
        self.label_img_gray.setGeometry(QtCore.QRect(650, 0, 640, 480))
        self.label_img_gray.setText("")
        self.label_img_gray.setObjectName("label_img_gray")

        self.retranslateUi(find_color_block)
        QtCore.QMetaObject.connectSlotsByName(find_color_block)

    def retranslateUi(self, find_color_block):
        _translate = QtCore.QCoreApplication.translate
        find_color_block.setWindowTitle(_translate("find_color_block", "Form"))
        self.groupBox_2.setTitle(_translate("find_color_block", "颜色选择"))
        self.checkBox_Red.setText(_translate("find_color_block", "red"))
        self.checkBox_Blue.setText(_translate("find_color_block", "blue"))
        self.checkBox_Yellow.setText(_translate("find_color_block", "yellow"))
        self.groupBox.setTitle(_translate("find_color_block", "HSV调整"))
        self.label_3.setText(_translate("find_color_block", "S 最大值"))
        self.label_7.setText(_translate("find_color_block", "HSV 范围"))
        self.label_5.setText(_translate("find_color_block", "V 最大值"))
        self.label_4.setText(_translate("find_color_block", "S 最小值"))
        self.label_2.setText(_translate("find_color_block", "H 最小值"))
        self.label.setText(_translate("find_color_block", "H 最大值"))
        self.label_6.setText(_translate("find_color_block", "V 最小值"))
